// quiz/src/components/Tab.vue
<template>
    <div className="tabPane">
        <TabButtons :tabOptions="tabOptions"
            :selection="currentTab"
            @on-selection="select"
        />

        <TabContent
            :contents="tabDisplayText"
            :currentTab="currentTab"
        />
    </div>
</template>

<script setup lang="ts">
    import { ref } from "vue";
    import TabButtons, { type TabButtonsProps} from "./TabButtons.vue"
    import TabContent, { type TabContentProps} from "./TabContent.vue";

    const tabOptions = ["tab 1", "tab 2", "tab 3", "tab 4"];
    const tabDisplayText = ["Texto do primeiro tab",
            "Texto do segundo tab",
            "Texto do terceiro tab",
            "Texto do quarto tab"];

    const currentTab = ref<number>();

    function select(tabIndex: number){
        currentTab.value = tabIndex;
    }

</script>

<style>

.tabPane{
    padding: 50px;
}

</style>

// quiz/src/components/tab.tsx
import React, { useState } from 'react';
import './tab.css';
import {TabButtons} from './TabButtons';
import {TabContent} from './TabContent';

const tabButtons = ["tab 1", "tab 2", "tab 3", "tab 4"];
const tabText = ["Texto do primeiro tab",
        "Texto do segundo tab",
        "Texto do terceiro tab",
        "Texto do quarto tab"];

export function Tab(){
    const [currentTab, setCurrentTab] = useState<number>();

    function select(tabIndex: number){
        setCurrentTab(tabIndex);
    }

    return(
        <div className='tabPane'>
            <TabButtons
                tabsOptions = { tabButtons }
                onSelection={ select }
                selection={ currentTab }
            />

            <TabContent
                contents={ tabText }
                currentTab={ currentTab }
            />
        </div>
    );
}
